### ISSUE TITLE
Investigate is_deprecated property

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/ottreeindex#13]
oti indexes a property called is_deprecated. This is not in the nexsons, so need to look at oti code to see how this is being determined. Also need to search client code for usage. Hoping we can simply deprecate this...

**Comment by jar398** [comment]
I looked briefly at the OTI sources. Tracing through the origin of this flag, I cannot find any place where it is set.

(The value comes from an isDeprecated flag for nexson elements, with getters and setters defined in ot-base. The setter isn't called anywhere, either in ot-base or in oti.)

Might be a good idea to scrub it.

**Comment by kcranston** [comment]
I'd say go ahead and scrub it if this was the only thing terribly wrong with the match_names response. Given the other issues [see gitter](https://gitter.im/OpenTreeOfLife/public?at=56f430817c18711013e64574) with this method, I vote to just leave it and clean it up with ottreeindex. That's probably only a week or two away.

**Comment by jar398** [comment]
It's the only thing of I know of that's 'terribly wrong', because oti now
scrubs the confusing and useless taxon properties. The same code could
scrub anything else pretty easily.

I'll put it lower priority than documentation review, but will make issue
so I don't forget.

**Comment by jar398** [comment]
I think the investigation is done, so close this issue at your leisure...

**Comment by jar398** [comment]
is_deprecated is now scrubbed from find_studies and find_trees results.

deployed on devapi.
