### ISSUE TITLE
Please index @label and @description for each tree 

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/ottreeindex#14]
These fields would be very helpful when retrieving a tree with `/v3/studies/find_tree`. This is how we add trees from any study (assuming we're not currently editing it) to a tree collection. The current index (oti) returns just the "raw" tree ID. I'd much rather store the friendlier name in `@label` in the collection JSON, as well as its `@description` text.

**Comment by kcranston** [comment]
You want to search by `label` and `description`, or you want these included in the returned fields for `find_trees` and `find_studies` when verbose=True?

**Comment by jimallman** [comment]
I mainly want these values in the verbose output. Thanks!

**Comment by kcranston** [comment]
See dup of this in [oti #42](https://github.com/OpenTreeOfLife/oti/issues/42)

**Comment by kcranston** [comment]
I am adding @label to the return values now. I am not sure what you mean by the `@description` text, though. What field is this in the curator UI?

**Comment by jimallman** [comment]
Hm, there's no such thing! I could have sworn we had a `@description` field for trees, but I don't see it in [the Nexson doc](https://github.com/OpenTreeOfLife/phylesystem-api/wiki/NexSON#table-i-predicate-vocabulary) or anywhere in the current phylesystem corpus.

Oh, it looks like we used to have this free-form tree description (as [seen in this screenshot](https://github.com/OpenTreeOfLife/opentree/issues/717#issuecomment-134669580)), but it was replaced by multiple controlled description fields like `ot:inferenceMethod` and `ot:branchLengthDescription `, as discussed in https://github.com/OpenTreeOfLife/opentree/issues/552 and https://github.com/OpenTreeOfLife/opentree/issues/555.

In any case, my intention was to get a reasonable default description for each tree, to be added to its entry in the decision list of a tree collection. Perhaps we can construct something useful from the inference-method and other fields? Suggestions welcome!

**Comment by kcranston** [comment]
This [commit](https://github.com/OpenTreeOfLife/ottreeindex/commit/dab6f7ae84fb427190c4d6f8523101980e7c1a9b) adds `@label` to the returned values for `find_trees`. Note that we also talked about adding a /meta option to the phylesystem-api GET methods that would let you get metadata for a specific tree (rather than using find_trees). See #19
